on: push

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: Login
      uses: okteto/login@master
      with:
        token: "Qr3GlqBiThEa29vSv9H1ucZHbDH8U4saOihi8KyEMJ7avQEa"

    - name: Deploy preview environment
      uses: okteto/deploy-preview@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: pr-${{ github.event.number }}-cindylopez
